### ISSUE TITLE
LibTask should have a sandbox

### ISSUE THREAD

**Issue by linuxcaffe** [kostajh/LibTask#1]
LibTask could be an awesome tool, who knows? 
If we could host an instance of a "sandbox" (disposable, play-data, available live and online) then anyone could try it/ test it.

**Comment by kostajh** [comment]
@linuxcaffe LibTask is not going to be anything more than a library that interfaces with Taskwarrior. To show do anything useful, you'd want to write other programs that utilize LibTask. As it happens, I have some plans for that, but to start with this library needs to be completed.

You can always clone the repo and run / modify the unit tests to see what you can do with it.
